# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "ZLSA Design"
license = "MIT"
licenselink = "https://github.com/zlsa/hugo-zlsadesign-theme/blob/master/LICENSE.md"
description = ""
homepage = "http://zlsadesign.com/"
tags = ["dark", "minimalistic"]
features = ["", ""]
min_version = 0.17

[author]
  name = "Jon Ross"
  homepage = "http://zlsadesign.com/"

